### ISSUE TITLE
New version 10.8.13

### ISSUE THREAD

**Issue by danbishop** [IsaacJT/jellyfin-snap#16]
Would it be possible to rebuild this snap so it pulls the latest Jellyfin (10.8.13)?

**Comment by IsaacJT** [comment]
I just promoted 10.8.13 from the `latest/edge` channel to `latest/stable` - enjoy :)

**Comment by danbishop** [comment]
Oh sorry, I hadn't realised it was already on edge. Amazing. Thanks Isaac :)
