### ISSUE TITLE
Upgrade to 10.9.1

### ISSUE THREAD

**Issue by danbishop** [IsaacJT/jellyfin-snap#19]
Hi Isaac,

Any chance of a rebuild to pull 10.9.1 to edge so we can start testing?

**Comment by danbishop** [comment]
Ahhhh sorry @IsaacJT, I wasn't sure if there were issues or you'd just not seen the latest release. Didn't mean to add any pressure :) 

If there's anything I can help with, do let me know.

**Comment by IsaacJT** [comment]
Hi @danbishop have you been able to use the version from `latest/edge`? I've now promoted it to `latest/candidate` as I'm working on upgrading to `core24` now

**Comment by IsaacJT** [comment]
Great! I've also pushed the new core24-based 10.9.8 to `latest/edge`. I'll close this issue
