### ISSUE TITLE
Version outdated 

### ISSUE THREAD

**Issue by jmgiaever** [IsaacJT/jellyfin-snap#2]
Hi,

Any plans on upgrading the snap to 10.8?

**Comment by IsaacJT** [comment]
Hi @jmgiaever, thanks for reminding me to update. I've updated the repo and will roll out the new versions as the snaps are built

**Comment by IsaacJT** [comment]
New versions have now been released

**Comment by jmgiaever** [comment]
Thank you very much. 

Just a quick question; is there a reason you've not updated? Don't you use it yourself?

**Comment by IsaacJT** [comment]
I do use it, I'm just currently travelling a lot and don't have the chance to use it often :)
