### ISSUE TITLE
Jellyfin doesn't allow me to install plugins

### ISSUE THREAD

**Issue by alculete** [IsaacJT/jellyfin-snap#25]
Jellyfin doesn't allow me to install plugins from the repository. Clicking nothing happens.

**Comment by jmgiaever** [comment]
What are you clicking? If you mean that plugins don't list, then it's most likely an IPv6 issue. 

It's a subject on this regarding IPv6, plugins and Jellyfin online.

**Comment by alculete** [comment]
The plugins appear, but clicking does nothing

**Comment by jmgiaever** [comment]
If you want this resolved, I suggest that you take your time to describe the issue better.

**Comment by alculete** [comment]
When you open the dashboard and then go to plugin repositories, for example, I want to install the Trakt plugin. I search for the plugin and I can find it. I click in install and nothing happens

**Comment by IsaacJT** [comment]
Hi @alculete sorry but I cannot reproduce this - I can install plugins (including Trakt) without any issues.

Can you please provide some more info on the environment you're running the snap on? OS version, snap version, etc.?
