### ISSUE TITLE
How to run in Ubuntu?

### ISSUE THREAD

**Issue by tazihad** [IsaacJT/jellyfin-snap#3]
I installed the snap version in Ubuntu 22.04. And now I am not sure how to run.

**Comment by IsaacJT** [comment]
Hi @zihadio, please see the Jellyfin docs: https://jellyfin.org/docs/general/quick-start.html

Once the snap is installed, you can start from step 3.

**Comment by zihadio** [comment]
@IsaacJT okay. I can see I can access to jellyfin from http://127.0.0.1:8096/. But I can't add any media folder for permission. It's empty. Any help?

**Comment by zrrion** [comment]
I am having the same issue. Permissions appear to be in order, same as yours, but it is unable to see the folder specified. If I cannot figure out what the issue is I am going to try pointing it at a network folder and seeing if that does anything

**Comment by IsaacJT** [comment]
Hi @zrrion and @tazihad,

What's the path to your media storage? You may need to connect the `removable-media` interface:

    snap connect itrue-jellyfin:removable-media 

This allows the snap to access `/media`, `/run/media` and `/mnt` (https://snapcraft.io/docs/removable-media-interface).

**Comment by IsaacJT** [comment]
I've added the `mount-observe` interface to the latest version (which should be published in the store edge channel once it's finished building). This should fix the drop-down menu in the web interface.

If you try it out, you will need to manually connect the interface (`snap connect itrue-jellyfin:mount-observe`) until I get the interface autoconnection approved by the store team.

**Comment by tazihad** [comment]
@IsaacJT I couldn't run the snap version. Now I have switched to docker version.
